# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py tinitaly
    uv run python source_unzip.py tinitaly
    uv run python source_bounds.py tinitaly
    uv run python source_polygonize.py tinitaly 32
    uv run python source_create_tarball.py tinitaly