# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_bounds.py es2b
    uv run python source_polygonize.py es2b 32
    uv run python source_create_tarball.py es2b