# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    # no public download yet
    uv run python source_to_cog.py es5b
    uv run python source_bounds.py es5b
    uv run python source_polygonize.py es5b 32
    uv run python source_create_tarball.py es5b