# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    # no public download yet
    uv run python source_to_cog.py itsicily
    uv run python source_bounds.py itsicily
    uv run python source_polygonize.py itsicily 32
    uv run python source_create_tarball.py itsicily