# Source preparation pipeline to be run from mapterhorn/pipelines folder

[no-cd]
default:
    uv run python source_download.py us1h
    uv run python source_unzip.py us1h
    uv run python source_verify_crs.py us1h
    uv run python source_slice.py us1h 16384
    uv run python source_to_cog.py us1h
    uv run python source_bounds.py us1h
    uv run python source_polygonize.py us1h 32
    uv run python source_create_tarball.py us1h