# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py au5/epsg28352
    uv run python source_unzip.py au5/epsg28352
    uv run python source_verify_crs.py au5/epsg28352
    uv run python source_slice.py au5/epsg28352 16384
    uv run python source_to_cog.py au5/epsg28352
    uv run python source_bounds.py au5/epsg28352
    uv run python source_polygonize.py au5/epsg28352 32
    uv run python source_create_tarball.py au5/epsg28352
