# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py atburgenland
    uv run python source_bounds.py atburgenland
    uv run python source_polygonize.py atburgenland 32
    uv run python source_create_tarball.py atburgenland