# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py debayern
    uv run python source_bounds.py debayern
    uv run python source_polygonize.py debayern 32
    uv run python source_create_tarball.py debayern