# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py at10
    uv run python source_bounds.py at10
    uv run python source_polygonize.py at10 32
    uv run python source_create_tarball.py at10