# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py is
    uv run python source_to_cog.py is
    uv run python source_bounds.py is
    uv run python source_polygonize.py is 32
    uv run python source_create_tarball.py is