# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py itsardegnaurban
    uv run python source_unzip.py itsardegnaurban
    uv run python source_bounds.py itsardegnaurban
    uv run python source_polygonize.py itsardegnaurban 32
    uv run python source_create_tarball.py itsardegnaurban