# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py deniedersachsen
    uv run python source_bounds.py deniedersachsen
    uv run python source_polygonize.py deniedersachsen 32
    uv run python source_create_tarball.py deniedersachsen