# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py frrgealti1metro
    uv run python source_unzip.py frrgealti1metro # translate only the .asc files
    uv run python source_set_crs.py frrgealti1metro EPSG:2154
    uv run python source_bounds.py frrgealti1metro
    uv run python source_polygonize.py frrgealti1metro 32
    uv run python source_create_tarball.py frrgealti1metro