# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py frrgealti5stpm
    uv run python source_unzip.py frrgealti5stpm
    uv run python source_set_crs.py frrgealti5stpm EPSG:4467
    uv run python source_bounds.py frrgealti5stpm
    uv run python source_polygonize.py frrgealti5stpm 32
    uv run python source_create_tarball.py frrgealti5stpm