# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_bounds.py es2c
    uv run python source_polygonize.py es2c 32
    uv run python source_create_tarball.py es2c