# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py beflanders
    uv run python source_bounds.py beflanders
    uv run python source_polygonize.py beflanders 12
    uv run python source_create_tarball.py beflanders