# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_unzip.py nosvalbard
    uv run python source_bounds.py nosvalbard
    uv run python source_polygonize.py nosvalbard 32
    uv run python source_create_tarball.py nosvalbard