# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py ee # rename files by hand
    uv run python source_bounds.py ee
    uv run python source_polygonize.py ee 32
    uv run python source_create_tarball.py ee