# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py usgsned13
    uv run python source_bounds.py usgsned13
    uv run python source_polygonize.py usgsned13 32
    uv run python source_create_tarball.py usgsned13
