# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py usgs3dep13
    uv run python source_to_cog.py usgs3dep13
    uv run python source_bounds.py usgs3dep13
    uv run python source_polygonize.py usgs3dep13 32
    uv run python source_create_tarball.py usgs3dep13
