# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py derlp
    uv run python source_bounds.py derlp
    uv run python source_polygonize.py derlp 32
    uv run python source_create_tarball.py derlp