# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    # no public download yet, only password-protected FTP access
    uv run python source_unzip.py dk # remove southern border files, wrong nodata value
    uv run python source_bounds.py dk
    uv run python source_polygonize.py dk 32
    uv run python source_create_tarball.py dk