# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_to_cog.py jpdem10a
    uv run python source_bounds.py jpdem10a
    uv run python source_polygonize.py jpdem10a 32
    uv run python source_create_tarball.py jpdem10a