# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py no
    uv run python source_to_cog.py no
    uv run python source_bounds.py no
    uv run python source_polygonize.py no 32
    uv run python source_create_tarball.py no