# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py debrandenburg
    uv run python source_unzip.py debrandenburg
    uv run python source_set_crs.py debrandenburg EPSG:25833
    uv run python source_bounds.py debrandenburg
    uv run python source_polygonize.py debrandenburg 32
    uv run python source_create_tarball.py debrandenburg