# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py swissalti3d
    uv run python source_bounds.py swissalti3d
    uv run python source_polygonize.py swissalti3d 32
    uv run python source_create_tarball.py swissalti3d