# Source preparation pipeline to be run from mapterhorn/pipelines folder

[no-cd]
default:
    uv run python source_download.py au5g
    uv run python source_unzip.py au5g
    uv run python source_slice.py au5g 16384
    uv run python source_to_cog.py au5g
    uv run python source_bounds.py au5g
    uv run python source_polygonize.py au5g 32
    uv run python source_create_tarball.py au5g
