# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py ro
    uv run python source_unzip_ro.py
    uv run python source_set_crs.py ro EPSG:3844
    uv run python source_fix_orientation.py ro
    uv run python source_bounds.py ro
    uv run python source_polygonize.py ro 32
    uv run python source_create_tarball.py ro