# Run full pipeline
default:
    # uv run python source_download.py glo30
    # uv run python source_download.py swissalti3d
    # uv run python source_download.py at10
    # uv run python source_download.py atburgenland
    # uv run python source_download.py atoberoesterreich
    # uv run python source_download.py atsalzburg
    # uv run python source_download.py atkaernten
    # uv run python source_download.py beflanders
    # uv run python source_download.py bewallonie
    # uv run python source_download.py cz
    # uv run python source_download.py debayern
    # uv run python source_download.py deniedersachsen
    # uv run python source_download.py ee
    # # rename ee files by hand
    # uv run python source_download.py tinitaly
    # uv run python source_download.py frrgealti5corse
    # uv run python source_download.py frrgealti5reunion
    # uv run python source_download.py frrgealti5caribbean
    # uv run python source_download.py frrgealti5stpm
    # uv run python source_download.py frrgealti5metro
    # uv run python source_download.py frrgealti5guiana
    # uv run python source_download.py frrgealti5mayotte
    # uv run python source_download.py demv
    # # rename demv files by hand
    # uv run python source_download.py deberlin
    # uv run python source_download.py debrandenburg
    # uv run python source_download.py desachsen
    # uv run python source_download.py dehamburg
    # uv run python source_download.py debremen
    # uv run python source_download.py dehessen
    # uv run python source_download.py lu
    # uv run python source_download.py desachsenanhalt
    # uv run python source_download.py denrw
    # uv run python source_download.py itaosta
    # uv run python source_download.py itbozen # no public download yet
    # uv run python source_download.py derlp
    # uv run python source_download.py dk # no public download yet
    # uv run python source_download.py si
    # uv run python source_download.py es5a # no public download yet
    # uv run python source_download.py es5b # no public download yet
    # uv run python source_download.py es5c # no public download yet
    # uv run python source_download.py es5d # no public download yet
    # uv run python source_download.py aalv
    # uv run python source_download.py ro
    # uv run python source_download.py debw
    # uv run python source_download.py desaarland
    # uv run python source_download.py dethueringen
    # uv run python source_download.py desh # rename files after download
    # uv run python source_download.py sk
    # uv run python source_download.py fi
    # uv run python source_download.py frrgealti1mayotte
    # uv run python source_download.py frrgealti1reunion
    # uv run python source_download.py frrgealti1guiana
    # uv run python source_download.py frrgealti1corse
    # uv run python source_download.py frrgealti1stpm
    # uv run python source_download.py frrgealti1caribbean
    # uv run python source_download.py frrgealti1metro
    # uv run python source_download.py itsardegnacostiera
    # uv run python source_download.py itsardegnaurban
    # uv run python source_download.py se # no public download yet
    # uv run python source_download.py itsicily # no public download yet
    # uv run python source_download.py nlahn5lowresfilled # no public download yet
    # uv run python source_download.py pl5
    # uv run python source_download.py pl1

    # uv run python source_unzip.py bewallonie
    # uv run python source_unzip.py cz
    # uv run python source_unzip.py tinitaly
    # uv run python source_unzip.py frrgealti5corse
    # uv run python source_unzip.py frrgealti5reunion
    # uv run python source_unzip.py frrgealti5caribbean
    # uv run python source_unzip.py frrgealti5stpm
    # uv run python source_unzip.py frrgealti5metro
    # uv run python source_unzip.py frrgealti5guiana
    # uv run python source_unzip.py frrgealti5mayotte
    # uv run python source_unzip.py deberlin
    # uv run python source_unzip.py debrandenburg
    # uv run python source_unzip.py desachsen
    # unzip dehamburg unzip by hand, it has a nested zip file
    # uv run python source_unzip.py debremen
    # uv run python source_unzip.py dehessen
    # uv run python source_unzip.py lu
    # rm source-store/lu/MNT_Z3_Z4_Luref_NGL.tif # this file has a different resolution
    # uv run python source_unzip.py desachsenanhalt
    # uv run python source_unzip.py itaosta
    # uv run python source_unzip.py itbozen
    # uv run python source_unzip.py dk # remove southern border files, wrong nodata value
    # uv run python source_unzip.py aalv # sparse txt file, convert to tif by filling a matrix
    # uv run python source_unzip_ro.py
    # uv run python source_unzip.py debw # translate only the .xyz files
    # uv run python source_unzip.py desaarland
    # uv run python source_unzip.py dethueringen
    # uv run python source_unzip.py sk # set crs to EPSG:5514
    # uv run python source_unzip.py frrgealti1mayotte # translate only the .asc files
    # uv run python source_unzip.py frrgealti1reunion # translate only the .asc files
    # uv run python source_unzip.py frrgealti1guiana # translate only the .asc files
    # uv run python source_unzip.py frrgealti1corse # translate only the .asc files
    # uv run python source_unzip.py frrgealti1stpm # translate only the .asc files
    # uv run python source_unzip.py frrgealti1caribbean # translate only the .asc files
    # uv run python source_unzip.py frrgealti1metro # translate only the .asc files
    # uv run python source_unzip.py itsardegnacostiera
    # uv run python source_unzip.py itsardegnaurban

    # uv run python source_to_cog.py bewallonie
    # uv run python source_to_cog.py dehamburg
    # uv run python source_to_cog.py si
    # uv run python source_to_cog.py es5a
    # uv run python source_to_cog.py es5b
    # uv run python source_to_cog.py es5c
    # uv run python source_to_cog.py es5d
    # uv run python source_to_cog.py aalv
    # uv run python source_to_cog.py desh
    # uv run python source_to_cog.py sk
    # uv run python source_to_cog.py se
    # uv run python source_to_cog.py itsicily
    # uv run python source_to_cog.py nlahn5lowresfilled
    # uv run python source_to_cog.py pl5 # remove zip files, remove wrongly tagged 1m files
    # uv run python source_to_cog.py pl1 # remove zip files

    # uv run python source_slice.py bewallonie 16384
    # uv run python source_to_cog.py bewallonie

    # uv run python source_slice.py sk 16384
    # uv run python source_to_cog.py sk

    # uv run python source_set_crs.py atsalzburg EPSG:31258
    # uv run python source_set_crs.py frrgealti5corse EPSG:2154
    # uv run python source_set_crs.py frrgealti5reunion EPSG:2975
    # uv run python source_set_crs.py frrgealti5caribbean EPSG:4559
    # uv run python source_set_crs.py frrgealti5stpm EPSG:4467
    # uv run python source_set_crs.py frrgealti5metro EPSG:2154
    # uv run python source_set_crs.py frrgealti5guiana EPSG:2972
    # uv run python source_set_crs.py frrgealti5mayotte EPSG:4471
    # uv run python source_set_crs.py deberlin EPSG:25833
    # uv run python source_set_crs.py dehamburg EPSG:25832
    # uv run python source_set_crs.py debremen EPSG:25832
    # uv run python source_set_crs.py dehessen EPSG:25832
    # uv run python source_set_crs.py desachsenanhalt EPSG:25832
    # uv run python source_set_crs.py si EPSG:3794
    # uv run python source_set_crs.py ro EPSG:3844
    # uv run python source_set_crs.py debw EPSG:25832
    # uv run python source_set_crs.py dethueringen EPSG:25832
    # uv run python source_set_crs.py desh EPSG:25832
    # uv run python source_set_crs.py frrgealti1mayotte EPSG:4471
    # uv run python source_set_crs.py frrgealti1reunion EPSG:2975
    # uv run python source_set_crs.py frrgealti1guiana EPSG:2972
    # uv run python source_set_crs.py frrgealti1corse EPSG:2154
    # uv run python source_set_crs.py frrgealti1stpm EPSG:4467
    # uv run python source_set_crs.py frrgealti1caribbean EPSG:4559
    # uv run python source_set_crs.py frrgealti1metro EPSG:2154
    # uv run python source_set_crs.py itsardegnacostiera EPSG:25832
    # uv run python source_set_crs.py debrandenburg EPSG:25833
    # uv run python source_set_crs.py pl5 EPSG:2180
    # uv run python source_set_crs.py pl1 EPSG:2180
    # uv run python source_set_crs.py itaosta EPSG:23032
    # uv run python source_set_crs.py atoberoesterreich EPSG:31255

    # uv run python source_set_nodata.py atkaernten 0.0
    # uv run python source_set_nodata.py demv -9999
    # uv run python source_set_nodata.py deberlin -9999
    # uv run python source_set_nodata.py dehamburg 0.0
    # uv run python source_set_nodata.py debremen 0.0
    # uv run python source_set_nodata.py dehessen -9999
    # uv run python source_set_nodata.py itbozen -9999
    # uv run python source_set_nodata.py si -9999
    # uv run python source_set_nodata.py debw 0.0
    # uv run python source_set_nodata.py dethueringen 0.0
    # uv run python source_set_nodata.py desh 0.0

    # uv run python source_fix_orientation.py deberlin
    # uv run python source_fix_orientation.py dehamburg
    # uv run python source_fix_orientation.py si
    # uv run python source_fix_orientation.py ro
    # uv run python source_fix_orientation.py debw

    # uv run python source_bounds.py glo30
    # uv run python source_bounds.py swissalti3d
    # uv run python source_bounds.py at10
    # uv run python source_bounds.py atburgenland
    # uv run python source_bounds.py atoberoesterreich
    # uv run python source_bounds.py atsalzburg
    # uv run python source_bounds.py atkaernten
    # uv run python source_bounds.py beflanders
    # uv run python source_bounds.py bewallonie
    # uv run python source_bounds.py cz
    # uv run python source_bounds.py debayern
    # uv run python source_bounds.py deniedersachsen
    # uv run python source_bounds.py ee
    # uv run python source_bounds.py tinitaly
    # uv run python source_bounds.py frrgealti5corse
    # uv run python source_bounds.py frrgealti5reunion
    # uv run python source_bounds.py frrgealti5caribbean
    # uv run python source_bounds.py frrgealti5stpm
    # uv run python source_bounds.py frrgealti5metro
    # uv run python source_bounds.py frrgealti5guiana
    # uv run python source_bounds.py frrgealti5mayotte
    # uv run python source_bounds.py demv
    # uv run python source_bounds.py deberlin
    # uv run python source_bounds.py debrandenburg
    # uv run python source_bounds.py desachsen
    # uv run python source_bounds.py dehamburg
    # uv run python source_bounds.py debremen
    # uv run python source_bounds.py dehessen
    # uv run python source_bounds.py lu
    # uv run python source_bounds.py desachsenanhalt
    # uv run python source_bounds.py denrw
    # uv run python source_bounds.py itaosta
    # uv run python source_bounds.py itbozen
    # uv run python source_bounds.py derlp
    # uv run python source_bounds.py dk
    # uv run python source_bounds.py si
    # uv run python source_bounds.py es5a
    # uv run python source_bounds.py es5b
    # uv run python source_bounds.py es5c
    # uv run python source_bounds.py es5d
    # uv run python source_bounds.py aalv
    # uv run python source_bounds.py ro
    # uv run python source_bounds.py debw
    # uv run python source_bounds.py desaarland
    # uv run python source_bounds.py dethueringen
    # uv run python source_bounds.py desh
    # uv run python source_bounds.py sk
    # uv run python source_bounds.py fi
    # uv run python source_bounds.py frrgealti1mayotte
    # uv run python source_bounds.py frrgealti1reunion
    # uv run python source_bounds.py frrgealti1guiana
    # uv run python source_bounds.py frrgealti1corse
    # uv run python source_bounds.py frrgealti1stpm
    # uv run python source_bounds.py frrgealti1caribbean
    # uv run python source_bounds.py frrgealti1metro
    # uv run python source_bounds.py itsardegnacostiera
    # uv run python source_bounds.py itsardegnaurban
    # uv run python source_bounds.py se
    # uv run python source_bounds.py itsicily
    # uv run python source_bounds.py nlahn5lowresfilled
    # uv run python source_bounds.py pl5
    # uv run python source_bounds.py pl1

    # uv run python source_polygonize.py frrgealti5stpm 32
    # uv run python source_polygonize.py frrgealti5mayotte 32
    # uv run python source_polygonize.py frrgealti5reunion 32
    # uv run python source_polygonize.py frrgealti5caribbean 32
    # uv run python source_polygonize.py frrgealti1stpm 32
    # uv run python source_polygonize.py aalv 32
    # uv run python source_polygonize.py atburgenland 32
    # uv run python source_polygonize.py debremen 32
    # uv run python source_polygonize.py frrgealti5corse 32
    # uv run python source_polygonize.py es5d 32
    # uv run python source_polygonize.py frrgealti1mayotte 32
    # uv run python source_polygonize.py dehamburg 32
    # uv run python source_polygonize.py deberlin 32
    # uv run python source_polygonize.py nlahn5lowresfilled 32 # fix compound CRS: ogr2ogr -f GPKG nlahn5lowresfilledfixed.gpkg nlahn5lowresfilled.gpkg -a_srs EPSG:28992
    # uv run python source_polygonize.py itaosta 32
    # uv run python source_polygonize.py at10 32
    # uv run python source_polygonize.py itbozen 32
    # uv run python source_polygonize.py itsardegnaurban 32
    # uv run python source_polygonize.py frrgealti1reunion 32
    # uv run python source_polygonize.py frrgealti1caribbean 32
    # uv run python source_polygonize.py cz 32
    # uv run python source_polygonize.py desaarland 32
    # uv run python source_polygonize.py es5c 32
    # uv run python source_polygonize.py frrgealti5guiana 32
    # uv run python source_polygonize.py lu 32
    # uv run python source_polygonize.py tinitaly 32
    # uv run python source_polygonize.py itsardegnacostiera 32
    # uv run python source_polygonize.py es5b 32
    # uv run python source_polygonize.py frrgealti1corse 32
    # uv run python source_polygonize.py desachsenanhalt 32
    # uv run python source_polygonize.py atkaernten 32
    # uv run python source_polygonize.py desachsen 32
    # uv run python source_polygonize.py debrandenburg 32
    # uv run python source_polygonize.py frrgealti5metro 32
    # uv run python source_polygonize.py demv 32
    # uv run python source_polygonize.py dehessen 32
    # uv run python source_polygonize.py itsicily 32
    # uv run python source_polygonize.py derlp 32
    # uv run python source_polygonize.py denrw 32
    # uv run python source_polygonize.py es5a 32
    # uv run python source_polygonize.py debw 32
    # uv run python source_polygonize.py ro 32
    # uv run python source_polygonize.py atsalzburg 32
    # uv run python source_polygonize.py ee 32
    # uv run python source_polygonize.py deniedersachsen 32
    # uv run python source_polygonize.py si 32
    # uv run python source_polygonize.py atoberoesterreich 32
    # uv run python source_polygonize.py dethueringen 32
    # uv run python source_polygonize.py frrgealti1guiana 32
    # uv run python source_polygonize.py desh 32
    # uv run python source_polygonize.py debayern 32
    # uv run python source_polygonize.py swissalti3d 32
    # uv run python source_polygonize.py dk 32
    # uv run python source_polygonize.py glo30 32
    # uv run python source_polygonize.py se 32 # fix compound CRS: ogr2ogr -f GPKG sefixed.gpkg se.gpkg -a_srs EPSG:3006
    # uv run python source_polygonize.py frrgealti1metro 32
    # uv run python source_polygonize.py fi 12
    # uv run python source_polygonize.py beflanders 12
    # uv run python source_polygonize.py bewallonie 32
    # uv run python source_polygonize.py sk 32
    # uv run python source_polygonize.py pl5 32
    # uv run python source_polygonize.py pl1 32

    # uv run python source_create_tarball.py frrgealti5stpm
    # uv run python source_create_tarball.py frrgealti5mayotte
    # uv run python source_create_tarball.py frrgealti5reunion
    # uv run python source_create_tarball.py frrgealti5caribbean
    # uv run python source_create_tarball.py frrgealti1stpm
    # uv run python source_create_tarball.py aalv
    # uv run python source_create_tarball.py atburgenland
    # uv run python source_create_tarball.py debremen
    # uv run python source_create_tarball.py frrgealti5corse
    # uv run python source_create_tarball.py es5d
    # uv run python source_create_tarball.py frrgealti1mayotte
    # uv run python source_create_tarball.py dehamburg
    # uv run python source_create_tarball.py deberlin
    # uv run python source_create_tarball.py nlahn5lowresfilled
    # uv run python source_create_tarball.py itaosta
    # uv run python source_create_tarball.py at10
    # uv run python source_create_tarball.py itbozen
    # uv run python source_create_tarball.py itsardegnaurban
    # uv run python source_create_tarball.py frrgealti1reunion
    # uv run python source_create_tarball.py frrgealti1caribbean
    # uv run python source_create_tarball.py cz
    # uv run python source_create_tarball.py desaarland
    # uv run python source_create_tarball.py es5c
    # uv run python source_create_tarball.py frrgealti5guiana
    # uv run python source_create_tarball.py lu
    # uv run python source_create_tarball.py tinitaly
    # uv run python source_create_tarball.py itsardegnacostiera
    # uv run python source_create_tarball.py es5b
    # uv run python source_create_tarball.py frrgealti1corse
    # uv run python source_create_tarball.py desachsenanhalt
    # uv run python source_create_tarball.py atkaernten
    # uv run python source_create_tarball.py desachsen
    # uv run python source_create_tarball.py debrandenburg
    # uv run python source_create_tarball.py frrgealti5metro
    # uv run python source_create_tarball.py demv
    # uv run python source_create_tarball.py dehessen
    # uv run python source_create_tarball.py itsicily
    # uv run python source_create_tarball.py derlp
    # uv run python source_create_tarball.py denrw
    # uv run python source_create_tarball.py es5a
    # uv run python source_create_tarball.py debw
    # uv run python source_create_tarball.py ro
    # uv run python source_create_tarball.py atsalzburg
    # uv run python source_create_tarball.py ee
    # uv run python source_create_tarball.py deniedersachsen
    # uv run python source_create_tarball.py si
    # uv run python source_create_tarball.py atoberoesterreich
    # uv run python source_create_tarball.py dethueringen
    # uv run python source_create_tarball.py frrgealti1guiana
    # uv run python source_create_tarball.py desh
    # uv run python source_create_tarball.py debayern
    # uv run python source_create_tarball.py swissalti3d
    # uv run python source_create_tarball.py dk
    # uv run python source_create_tarball.py glo30
    # uv run python source_create_tarball.py se
    # uv run python source_create_tarball.py frrgealti1metro
    # uv run python source_create_tarball.py fi
    # uv run python source_create_tarball.py beflanders
    # uv run python source_create_tarball.py bewallonie
    # uv run python source_create_tarball.py sk
    # uv run python source_create_tarball.py pl5
    # uv run python source_create_tarball.py pl1

    # uv run python aggregation_covering.py
    # uv run python downsampling_covering.py
 
    # uv run python aggregation_run.py
    # uv run python downsampling_run.py
    # uv run python remove_dangling_pmtiles.py
    # uv run python create_index.py

    # TMPDIR=/tmp uv run python bundle.py
    # uv run python download_urls.py 0.0.0
    # uv run python attribution.py
    # java -cp planetiler.jar Coverage.java # cf https://github.com/onthegomap/planetiler-examples

# Run debug pipeline
debug:
    uv run python source_download.py debug-glo30
    uv run python source_download.py debug-swissalti3d
    
    uv run python source_bounds.py debug-glo30
    uv run python source_bounds.py debug-swissalti3d
    
    uv run python aggregation_covering.py
    uv run python downsampling_covering.py
    
    uv run python aggregation_run.py
    uv run python downsampling_run.py

    uv run python remove_dangling_pmtiles.py
    TMPDIR=/tmp uv run python bundle.py 0.0.0
    uv run python download_urls.py 0.0.0
    uv run python attribution.py

# Upload to cloudflare. Requires the following env variables:
# export AWS_ACCESS_KEY_ID=MY_KEY
# export AWS_SECRET_ACCESS_KEY=MY_SECRET
upload:
    pmtiles upload bundle-store/planet/planet.pmtiles planet.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"

    pmtiles upload bundle-store/6-33-21/6-33-21.pmtiles 6-33-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-36-18/6-36-18.pmtiles 6-36-18.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-37-18/6-37-18.pmtiles 6-37-18.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-37-17/6-37-17.pmtiles 6-37-17.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-22/6-35-22.pmtiles 6-35-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-17/6-35-17.pmtiles 6-35-17.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-36-19/6-36-19.pmtiles 6-36-19.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-14/6-35-14.pmtiles 6-35-14.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-29-26/6-29-26.pmtiles 6-29-26.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-37-14/6-37-14.pmtiles 6-37-14.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-31-22/6-31-22.pmtiles 6-31-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-32-21/6-32-21.pmtiles 6-32-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-19/6-35-19.pmtiles 6-35-19.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-34-23/6-34-23.pmtiles 6-34-23.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-33-24/6-33-24.pmtiles 6-33-24.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-22-30/6-22-30.pmtiles 6-22-30.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-31-21/6-31-21.pmtiles 6-31-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-34-19/6-34-19.pmtiles 6-34-19.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-24/6-35-24.pmtiles 6-35-24.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-37-15/6-37-15.pmtiles 6-37-15.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-22-31/6-22-31.pmtiles 6-22-31.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-18/6-35-18.pmtiles 6-35-18.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-36-21/6-36-21.pmtiles 6-36-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-34-20/6-34-20.pmtiles 6-34-20.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-32-24/6-32-24.pmtiles 6-32-24.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-36-22/6-36-22.pmtiles 6-36-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-31-24/6-31-24.pmtiles 6-31-24.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-30-24/6-30-24.pmtiles 6-30-24.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-34-24/6-34-24.pmtiles 6-34-24.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-34-21/6-34-21.pmtiles 6-34-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-36-14/6-36-14.pmtiles 6-36-14.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-41-35/6-41-35.pmtiles 6-41-35.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-36-17/6-36-17.pmtiles 6-36-17.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-21/6-35-21.pmtiles 6-35-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-16/6-35-16.pmtiles 6-35-16.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-20-28/6-20-28.pmtiles 6-20-28.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-23/6-35-23.pmtiles 6-35-23.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-36-16/6-36-16.pmtiles 6-36-16.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-31-23/6-31-23.pmtiles 6-31-23.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-40-34/6-40-34.pmtiles 6-40-34.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-32-22/6-32-22.pmtiles 6-32-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-36-15/6-36-15.pmtiles 6-36-15.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-30-23/6-30-23.pmtiles 6-30-23.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-21-29/6-21-29.pmtiles 6-21-29.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-28-26/6-28-26.pmtiles 6-28-26.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-21-22/6-21-22.pmtiles 6-21-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-33-22/6-33-22.pmtiles 6-33-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-33-19/6-33-19.pmtiles 6-33-19.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-22-22/6-22-22.pmtiles 6-22-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-15/6-35-15.pmtiles 6-35-15.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-30-25/6-30-25.pmtiles 6-30-25.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-34-25/6-34-25.pmtiles 6-34-25.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-34-22/6-34-22.pmtiles 6-34-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-39-34/6-39-34.pmtiles 6-39-34.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-37-16/6-37-16.pmtiles 6-37-16.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-33-20/6-33-20.pmtiles 6-33-20.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-31-25/6-31-25.pmtiles 6-31-25.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-33-23/6-33-23.pmtiles 6-33-23.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-32-23/6-32-23.pmtiles 6-32-23.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"

    pmtiles upload bundle-store/attribution.json attribution.json --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/download_urls.json download_urls.json --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/coverage.pmtiles coverage.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
