# Run full pipeline
default:
    # uv run python source_download.py glo30
    # uv run python source_download.py swissalti3d
    # uv run python source_download.py at10
    # uv run python source_download.py atburgenland
    # uv run python source_download.py atoberoesterreich
    # uv run python source_download.py atsalzburg
    # uv run python source_download.py atkaernten
    # uv run python source_download.py beflanders
    # uv run python source_download.py bewallonie
    # uv run python source_download.py cz
    # uv run python source_download.py debayern
    # uv run python source_download.py deniedersachsen
    # uv run python source_download.py ee
    # uv run python source_download.py tinitaly
    # uv run python source_download.py frrgealti5corse
    # uv run python source_download.py frrgealti5reunion
    # uv run python source_download.py frrgealti5caribbean
    # uv run python source_download.py frrgealti5stpm
    # uv run python source_download.py frrgealti5metro
    # uv run python source_download.py frrgealti5guiana
    # uv run python source_download.py frrgealti5mayotte
    # uv run python source_download.py demv
    # uv run python source_download.py deberlin
    # uv run python source_download.py debrandenburg
    # uv run python source_download.py desachsen

    # uv run python source_unzip.py bewallonie
    # uv run python source_unzip.py cz
    # uv run python source_unzip.py tinitaly
    # uv run python source_unzip.py frrgealti5corse
    # uv run python source_unzip.py frrgealti5reunion
    # uv run python source_unzip.py frrgealti5caribbean
    # uv run python source_unzip.py frrgealti5stpm
    # uv run python source_unzip.py frrgealti5metro
    # uv run python source_unzip.py frrgealti5guiana
    # uv run python source_unzip.py frrgealti5mayotte
    # uv run python source_unzip.py deberlin
    # uv run python source_unzip.py debrandenburg
    # uv run python source_unzip.py desachsen

    # uv run python source_to_cog.py bewallonie

    # uv run python source_set_crs.py atsalzburg EPSG:31258
    # uv run python source_set_crs.py frrgealti5corse EPSG:2154
    # uv run python source_set_crs.py frrgealti5reunion EPSG:2975
    # uv run python source_set_crs.py frrgealti5caribbean EPSG:4559
    # uv run python source_set_crs.py frrgealti5stpm EPSG:4467
    # uv run python source_set_crs.py frrgealti5metro EPSG:2154
    # uv run python source_set_crs.py frrgealti5guiana EPSG:2972
    # uv run python source_set_crs.py frrgealti5mayotte EPSG:4471
    # uv run python source_set_crs.py deberlin EPSG:25833

    # uv run python source_set_nodata.py atkaernten 0.0
    # uv run python source_set_nodata.py demv -9999
    # uv run python source_set_nodata.py deberlin -9999

    # uv run python source_fix_orientation.py deberlin

    # uv run python source_bounds.py glo30
    # uv run python source_bounds.py swissalti3d
    # uv run python source_bounds.py at10
    # uv run python source_bounds.py atburgenland
    # uv run python source_bounds.py atoberoesterreich
    # uv run python source_bounds.py atsalzburg
    # uv run python source_bounds.py atkaernten
    # uv run python source_bounds.py beflanders
    # uv run python source_bounds.py bewallonie
    # uv run python source_bounds.py cz
    # uv run python source_bounds.py debayern
    # uv run python source_bounds.py niedersachsen
    # uv run python source_bounds.py ee
    # uv run python source_bounds.py tinitaly
    # uv run python source_bounds.py frrgealti5corse
    # uv run python source_bounds.py frrgealti5reunion
    # uv run python source_bounds.py frrgealti5carribean
    # uv run python source_bounds.py frrgealti5stpm
    # uv run python source_bounds.py frrgealti5metro
    # uv run python source_bounds.py frrgealti5guiana
    # uv run python source_bounds.py frrgealti5mayotte
    # uv run python source_bounds.py demv
    # uv run python source_bounds.py deberlin
    # uv run python source_bounds.py debrandenburg
    # uv run python source_bounds.py desachsen

    # uv run python aggregation_covering.py
    # uv run python downsampling_covering.py
 
    # uv run python aggregation_run.py
    # uv run python downsampling_run.py
    # uv run python remove_dangling_pmtiles.py
    # uv run python create_index.py

    # TMPDIR=/tmp uv run python bundle.py 0.0.0
    # uv run python download_urls.py 0.0.0
    # uv run python attribution.py

# Run debug pipeline
debug:
    uv run python source_download.py debug-glo30
    uv run python source_download.py debug-swissalti3d
    
    uv run python source_bounds.py debug-glo30
    uv run python source_bounds.py debug-swissalti3d
    
    uv run python aggregation_covering.py
    uv run python downsampling_covering.py
    
    uv run python aggregation_run.py
    uv run python downsampling_run.py

    uv run python remove_dangling_pmtiles.py
    TMPDIR=/tmp uv run python bundle.py 0.0.0
    uv run python download_urls.py 0.0.0
    uv run python attribution.py

# Upload to cloudflare. Requires the following env variables:
# export AWS_ACCESS_KEY_ID=MY_KEY
# export AWS_SECRET_ACCESS_KEY=MY_SECRET
upload:
    pmtiles upload bundle-store/planet/planet.pmtiles planet.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"

    pmtiles upload bundle-store/6-33-21/6-33-21.pmtiles 6-33-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-33-22/6-33-22.pmtiles 6-33-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-34-21/6-34-21.pmtiles 6-34-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-34-22/6-34-22.pmtiles 6-34-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-21/6-35-21.pmtiles 6-35-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-22/6-35-22.pmtiles 6-35-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"

    pmtiles upload bundle-store/attribution.json attribution.json --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/download_urls.json download_urls.json --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
