# Run full pipeline
default:
    # uv run python source_download.py glo30
    # uv run python source_download.py swissalti3d
    # uv run python source_download.py at10
    # uv run python source_download.py atburgenland
    # uv run python source_download.py atoberoesterreich
    # uv run python source_download.py atsalzburg
    # uv run python source_download.py atkaernten
    # uv run python source_download.py beflanders
    # uv run python source_download.py bewallonie
    # uv run python source_download.py cz
    # uv run python source_download.py debayern
    # uv run python source_download.py deniedersachsen
    # uv run python source_download.py ee
    # # rename ee files by hand
    # uv run python source_download.py tinitaly
    # uv run python source_download.py frrgealti5corse
    # uv run python source_download.py frrgealti5reunion
    # uv run python source_download.py frrgealti5caribbean
    # uv run python source_download.py frrgealti5stpm
    # uv run python source_download.py frrgealti5metro
    # uv run python source_download.py frrgealti5guiana
    # uv run python source_download.py frrgealti5mayotte
    # uv run python source_download.py demv
    # # rename demv files by hand
    # uv run python source_download.py deberlin
    # uv run python source_download.py debrandenburg
    # uv run python source_download.py desachsen
    # uv run python source_download.py dehamburg
    # uv run python source_download.py debremen
    # uv run python source_download.py dehessen
    # uv run python source_download.py lu
    # uv run python source_download.py desachsenanhalt
    # uv run python source_download.py denrw
    # uv run python source_download.py itaosta
    # uv run python source_download.py itbozen # no public download yet
    # uv run python source_download.py derlp
    # uv run python source_download.py dk # no public download yet
    # uv run python source_download.py si
    # uv run python source_download.py es5a # no public download yet
    # uv run python source_download.py es5b # no public download yet
    # uv run python source_download.py es5c # no public download yet
    # uv run python source_download.py es5d # no public download yet
    # uv run python source_download.py aalv

    # uv run python source_unzip.py bewallonie
    # uv run python source_unzip.py cz
    # uv run python source_unzip.py tinitaly
    # uv run python source_unzip.py frrgealti5corse
    # uv run python source_unzip.py frrgealti5reunion
    # uv run python source_unzip.py frrgealti5caribbean
    # uv run python source_unzip.py frrgealti5stpm
    # uv run python source_unzip.py frrgealti5metro
    # uv run python source_unzip.py frrgealti5guiana
    # uv run python source_unzip.py frrgealti5mayotte
    # uv run python source_unzip.py deberlin
    # uv run python source_unzip.py debrandenburg
    # uv run python source_unzip.py desachsen
    # unzip dehamburg unzip by hand, it has a nested zip file
    # uv run python source_unzip.py debremen
    # uv run python source_unzip.py dehessen
    # uv run python source_unzip.py lu
    # rm source-store/lu/MNT_Z3_Z4_Luref_NGL.tif # this file has a different resolution
    # uv run python source_unzip.py desachsenanhalt
    # uv run python source_unzip.py itaosta
    # uv run python source_unzip.py itbozen
    # uv run python source_unzip.py dk # remove southern border files, wrong nodata value
    # uv run python source_unzip.py aalv # sparse txt file, convert to tif by filling a matrix

    # uv run python source_to_cog.py bewallonie
    # uv run python source_to_cog.py dehamburg
    # uv run python source_to_cog.py si
    # uv run python source_to_cog.py es5a
    # uv run python source_to_cog.py es5b
    # uv run python source_to_cog.py es5c
    # uv run python source_to_cog.py es5d
    # uv run python source_to_cog.py aalv

    # uv run python source_set_crs.py atsalzburg EPSG:31258
    # uv run python source_set_crs.py frrgealti5corse EPSG:2154
    # uv run python source_set_crs.py frrgealti5reunion EPSG:2975
    # uv run python source_set_crs.py frrgealti5caribbean EPSG:4559
    # uv run python source_set_crs.py frrgealti5stpm EPSG:4467
    # uv run python source_set_crs.py frrgealti5metro EPSG:2154
    # uv run python source_set_crs.py frrgealti5guiana EPSG:2972
    # uv run python source_set_crs.py frrgealti5mayotte EPSG:4471
    # uv run python source_set_crs.py deberlin EPSG:25833
    # uv run python source_set_crs.py dehamburg EPSG:25832
    # uv run python source_set_crs.py debremen EPSG:25832
    # uv run python source_set_crs.py dehessen EPSG:25832
    # uv run python source_set_crs.py desachsenanhalt EPSG:25832
    # uv run python source_set_crs.py si EPSG:3794

    # uv run python source_set_nodata.py atkaernten 0.0
    # uv run python source_set_nodata.py demv -9999
    # uv run python source_set_nodata.py deberlin -9999
    # uv run python source_set_nodata.py dehamburg 0.0
    # uv run python source_set_nodata.py debremen 0.0
    # uv run python source_set_nodata.py dehessen -9999
    # uv run python source_set_nodata.py itbozen -9999
    # uv run python source_set_nodata.py si -9999

    # uv run python source_fix_orientation.py deberlin
    # uv run python source_fix_orientation.py dehamburg
    # uv run python source_fix_orientation.py si

    # uv run python source_bounds.py glo30
    # uv run python source_bounds.py swissalti3d
    # uv run python source_bounds.py at10
    # uv run python source_bounds.py atburgenland
    # uv run python source_bounds.py atoberoesterreich
    # uv run python source_bounds.py atsalzburg
    # uv run python source_bounds.py atkaernten
    # uv run python source_bounds.py beflanders
    # uv run python source_bounds.py bewallonie
    # uv run python source_bounds.py cz
    # uv run python source_bounds.py debayern
    # uv run python source_bounds.py niedersachsen
    # uv run python source_bounds.py ee
    # uv run python source_bounds.py tinitaly
    # uv run python source_bounds.py frrgealti5corse
    # uv run python source_bounds.py frrgealti5reunion
    # uv run python source_bounds.py frrgealti5caribbean
    # uv run python source_bounds.py frrgealti5stpm
    # uv run python source_bounds.py frrgealti5metro
    # uv run python source_bounds.py frrgealti5guiana
    # uv run python source_bounds.py frrgealti5mayotte
    # uv run python source_bounds.py demv
    # uv run python source_bounds.py deberlin
    # uv run python source_bounds.py debrandenburg
    # uv run python source_bounds.py desachsen
    # uv run python source_bounds.py dehamburg
    # uv run python source_bounds.py debremen
    # uv run python source_bounds.py dehessen
    # uv run python source_bounds.py lu
    # uv run python source_bounds.py desachsenanhalt
    # uv run python source_bounds.py denrw
    # uv run python source_bounds.py itaosta
    # uv run python source_bounds.py itbozen
    # uv run python source_bounds.py derlp
    # uv run python source_bounds.py dk
    # uv run python source_bounds.py si
    # uv run python source_bounds.py es5a
    # uv run python source_bounds.py es5b
    # uv run python source_bounds.py es5c
    # uv run python source_bounds.py es5d
    # uv run python source_bounds.py aalv

    # uv run python aggregation_covering.py
    # uv run python downsampling_covering.py
 
    # uv run python aggregation_run.py
    # uv run python downsampling_run.py
    # uv run python remove_dangling_pmtiles.py
    # uv run python create_index.py

    # TMPDIR=/tmp uv run python bundle.py 0.0.0
    # uv run python download_urls.py 0.0.0
    # uv run python attribution.py

# Run debug pipeline
debug:
    uv run python source_download.py debug-glo30
    uv run python source_download.py debug-swissalti3d
    
    uv run python source_bounds.py debug-glo30
    uv run python source_bounds.py debug-swissalti3d
    
    uv run python aggregation_covering.py
    uv run python downsampling_covering.py
    
    uv run python aggregation_run.py
    uv run python downsampling_run.py

    uv run python remove_dangling_pmtiles.py
    TMPDIR=/tmp uv run python bundle.py 0.0.0
    uv run python download_urls.py 0.0.0
    uv run python attribution.py

# Upload to cloudflare. Requires the following env variables:
# export AWS_ACCESS_KEY_ID=MY_KEY
# export AWS_SECRET_ACCESS_KEY=MY_SECRET
upload:
    pmtiles upload bundle-store/planet/planet.pmtiles planet.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"

    pmtiles upload bundle-store/6-33-21/6-33-21.pmtiles 6-33-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-33-22/6-33-22.pmtiles 6-33-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-34-21/6-34-21.pmtiles 6-34-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-34-22/6-34-22.pmtiles 6-34-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-21/6-35-21.pmtiles 6-35-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-22/6-35-22.pmtiles 6-35-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"

    pmtiles upload bundle-store/attribution.json attribution.json --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/download_urls.json download_urls.json --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
