# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py dethueringen
    uv run python source_unzip.py dethueringen
    uv run python source_set_crs.py dethueringen EPSG:25832
    uv run python source_set_nodata.py dethueringen 0.0
    uv run python source_bounds.py dethueringen
    uv run python source_polygonize.py dethueringen 32
    uv run python source_create_tarball.py dethueringen