# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py frrgealti5mayotte
    uv run python source_unzip.py frrgealti5mayotte
    uv run python source_set_crs.py frrgealti5mayotte EPSG:4471
    uv run python source_bounds.py frrgealti5mayotte
    uv run python source_polygonize.py frrgealti5mayotte 32
    uv run python source_create_tarball.py frrgealti5mayotte