# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py fi
    uv run python source_bounds.py fi
    uv run python source_polygonize.py fi 12
    uv run python source_create_tarball.py fi