# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py debug-swissalti3d
    uv run python source_bounds.py debug-swissalti3d
    uv run python source_polygonize.py debug-swissalti3d 32
    uv run python source_create_tarball.py debug-swissalti3d