# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py debug-glo30
    uv run python source_bounds.py debug-glo30
    uv run python source_polygonize.py debug-glo30 32
    uv run python source_create_tarball.py debug-glo30