# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py lu
    uv run python source_unzip.py lu
    rm source-store/lu/MNT_Z3_Z4_Luref_NGL.tif # this file has a different resolution
    uv run python source_bounds.py lu
    uv run python source_polygonize.py lu 32
    uv run python source_create_tarball.py lu
    