# Source preparation pipeline to be run from mapterhorn/pipelines folder

[no-cd]
default:
    uv run python source_download.py au5e
    uv run python source_unzip.py au5e
    uv run python source_bounds.py au5e
    uv run python source_polygonize.py au5e 32
    uv run python source_create_tarball.py au5e
