# Source preparation pipeline to be run from mapterhorn/pipelines folder

[no-cd]
default:
    uv run python source_download.py us1la
    uv run python source_to_cog.py us1la
    uv run python source_bounds.py us1la
    uv run python source_polygonize.py us1la 32
    uv run python source_create_tarball.py us1la
