# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py atoberoesterreich
    uv run python source_set_crs.py atoberoesterreich EPSG:31255
    uv run python source_bounds.py atoberoesterreich
    uv run python source_polygonize.py atoberoesterreich 32
    uv run python source_create_tarball.py atoberoesterreich