# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py desaarland
    uv run python source_unzip.py desaarland
    uv run python source_bounds.py desaarland
    uv run python source_polygonize.py desaarland 32
    uv run python source_create_tarball.py desaarland