# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py frrgealti1reunion
    uv run python source_unzip.py frrgealti1reunion # translate only the .asc files
    uv run python source_set_crs.py frrgealti1reunion EPSG:2975
    uv run python source_bounds.py frrgealti1reunion
    uv run python source_polygonize.py frrgealti1reunion 32
    uv run python source_create_tarball.py frrgealti1reunion