# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py demv # rename demv files by hand
    uv run python source_set_nodata.py demv -9999
    uv run python source_bounds.py demv
    uv run python source_polygonize.py demv 32
    uv run python source_create_tarball.py demv