# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py dehessen
    uv run python source_unzip.py dehessen
    uv run python source_set_crs.py dehessen EPSG:25832
    uv run python source_set_nodata.py dehessen -9999
    uv run python source_bounds.py dehessen
    uv run python source_polygonize.py dehessen 32
    uv run python source_create_tarball.py dehessen
